config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :dashboards
  resources :sessions
  resources :password_resets

  root to: 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
	has_one :user_role
	has_many :users, through: :user_role
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	before_create { generate_token(:auth_token) }

	has_one :user_role
	has_one :role, through: :user_role

	def send_password_reset
	  generate_token(:password_reset_token)
	  self.password_reset_sent_at = Time.zone.now
	  save!
	  UserMailer.password_reset(self).deliver
	end

	def generate_token(column)
	  begin
	    self[column] = SecureRandom.urlsafe_base64
	  end while User.exists?(column => self[column])
	end
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	include Pundit
	private
		def logged_in?
  		@current_user ||= User.find(session[:user_id]) if session[:user_id]
		end

		def current_user
			# User.find(session[:user_id]) if session[:user_id]
			@current_user ||= User.find_by_auth_token!(session[:auth_token]) if session[:auth_token]
		end

		def authenticate
			if current_user.present?
				current_user
			else
				redirect_to root_path, notice: 'Please Login first'
			end
		end

		helper_method :logged_in?
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate
  before_action :set_dashboard, only: [:show, :edit, :update, :destroy]

  # GET /dashboards
  # GET /dashboards.json
  def index
    @current_user = current_user
    @dashboards = Dashboard.all
  end

  # GET /dashboards/1
  # GET /dashboards/1.json
  def show
  end

  # GET /dashboards/new
  def new
    @dashboard = Dashboard.new
  end

  # GET /dashboards/1/edit
  def edit
  end

  # POST /dashboards
  # POST /dashboards.json
  def create
    @dashboard = Dashboard.new(dashboard_params)

    respond_to do |format|
      if @dashboard.save
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully created.' }
        format.json { render :show, status: :created, location: @dashboard }
      else
        format.html { render :new }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashboards/1
  # PATCH/PUT /dashboards/1.json
  def update
    respond_to do |format|
      if @dashboard.update(dashboard_params)
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @dashboard }
      else
        format.html { render :edit }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboards/1
  # DELETE /dashboards/1.json
  def destroy
    @dashboard.destroy
    respond_to do |format|
      format.html { redirect_to dashboards_url, notice: 'Dashboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dashboard
      @dashboard = Dashboard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dashboard_params
      params.fetch(:dashboard, {})
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

	def create
	  user = User.find_by_email(params[:email])
	  user.send_password_reset if user
	  redirect_to root_url, :notice => "Email sent with password reset instructions."
	end

	def edit
	  @user = User.find_by_password_reset_token!(params[:id])
	end

	# def update
	#   @user = User.find_by_password_reset_token!(params[:id])
	#   if @user.password_reset_sent_at < 2.hours.ago
	#     redirect_to new_password_reset_path, :alert => "Password reset has expired."
	#   elsif @user.update_attributes(params[:user])
	#     redirect_to root_url, :notice => "Password has been reset!"
	#   else
	#     render :edit
	#   end
	# end

	def update
	  @user = User.find_by_password_reset_token!(params[:id])
	  if @user.password_reset_sent_at < 2.hour.ago
	    flash[:notice] = 'Password reset has expired'
	    redirect_to new_password_reset_path, :alert => "Password reset has expired."
	  elsif @user.update(user_params)
	    flash[:notice] = 'Password has been reset!'
	    redirect_to root_url
	  else
	    render :edit
	  end
	end

	private
	  # Never trust parameters from the scary internet, only allow the white list through.
	  def user_params
	    params.require(:user).permit(:password)
	  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

	# def create
	#   user = User.find_by(email: params[:email])
	#   if user && user.authenticate(params[:password])
	#     session[:user_id] = user.id
	#     redirect_to dashboards_path, notice: 'Logged in!'
	#   else
	#     flash.now.alert = 'Email or password is invalid'
	#     render :new
	#   end
	# end

	def create
	  user = User.find_by_email(params[:email])
	  if user && user.authenticate(params[:password])
      session[:auth_token] = user.auth_token
      session[:user_id] = user.id
	    redirect_to dashboards_path, :notice => "Logged in!"
	  else
	    flash.now.alert = "Invalid email or password"
	    render "new"
	  end
	end

	def destroy
	  session[:user_id] = nil
	  redirect_to root_url, notice: 'Logged out!'
	end

end

app/controllers/users_controller.rb
# class for user
class UsersController < ApplicationController
  before_action :authenticate, except: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
      	session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboards/_form.html.erb
<%= form_with(model: dashboard, local: true) do |form| %>
  <% if dashboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dashboard.errors.count, "error") %> prohibited this dashboard from being saved:</h2>

      <ul>
      <% dashboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dashboards/edit.html.erb
<h1>Editing Dashboard</h1>

<%= render 'form', dashboard: @dashboard %>

<%= link_to 'Show', @dashboard %> |
<%= link_to 'Back', dashboards_path %>

app/views/dashboards/index.html.erb
<h1>Dashboard</h1>
<div id="Dashboard">
  <h2>Welcome <%= @current_user.name %></h2>
</div>

app/views/dashboards/new.html.erb
<h1>New Dashboard</h1>

<%= render 'form', dashboard: @dashboard %>

<%= link_to 'Back', dashboards_path %>

app/views/dashboards/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_dashboard_path(@dashboard) %> |
<%= link_to 'Back', dashboards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>stuffstr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="container">
      <div id="user_header">
        <% if logged_in? %>
          <%= link_to 'Logout', logout_path %>
        <% else %>
          <%= link_to "Sign Up", signup_path %>
          <%= link_to "Log In", login_path %>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/password_resets/edit.html.erb
<div class="sidenav">
  <div class="login-main-text">
    <h2>Password Edit page</h2>
    <p>You can Edit your password from here.</p>
  </div>
</div>


<div class="main">
  <div class="col-md-6 col-sm-12">
    <div class="register-form">
      <%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
        <% if @user.errors.any? %>
          <div class="error_messages">
            <h2>Form is invalid</h2>
            <ul>
              <% for message in @user.errors.full_messages %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation %>
        </div>
        <div><%= f.submit "Update Password", class: "btn btn-black" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/password_resets/new.html.erb
<div class="sidenav">
  <div class="login-main-text">
    <h2>Password reset Page</h2>
    <p>You can reset your password from here.</p>
  </div>
</div>


<div class="main">
  <div class="col-md-6 col-sm-12">
  	<div class="register-form">
			<%= form_tag password_resets_path, :method => :post do %>
			  <div class="form-group">
			    <%= label_tag :email %>
			    <%= text_field_tag :email, params[:email] %>
			  </div>
			  <div><%= submit_tag "Reset Password", class: "btn btn-black" %></div>
			<% end %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="sidenav">
  <div class="login-main-text">
    <h2>Application Register Page</h2>
    <p>Register from here to access.</p>
    <div>
    	All ready have account?
    	<%= link_to "Log In", login_path , class: "btn btn-primary" %>
  	</div>
  </div>
</div>

<div class="main">
  <div class="col-md-6 col-sm-12">
    <div class="register-form">
      <%= form_for @user do |f| %>
			  <div>
				  <% if @user.errors.any? %>
				    <div class="error_messages">
				      <h2>Form is invalid</h2>
				      <ul>
				        <% @user.errors.full_messages.each do |message| %>
				          <li><%= message %></li>
				        <% end %>
				      </ul>
				    </div>
				  <% end %>
			  </div>
        <div class="form-group">
           <%= f.label :name %><br />
           <%= f.text_field :name %>
        </div>
        <div class="form-group">
           <%= f.label :email %><br />
           <%= f.text_field :email %>
        </div>
        <div class="form-group">
           <%= f.label :password %><br />
           <%= f.password_field :password %>
        </div>
        <div class="form-group">
           <%= f.label :password_confirmation %><br />
           <%= f.password_field :password_confirmation %>
        </div>
        <%= f.submit "Sign Up", class: "btn btn-black" %>
      <% end %>
    </div>
   </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>